name: angular_dart_demo
version: 0.0.1
dependencies:
  angular: '>=0.12.0'
  browser: any
  http_server: any
  js: any
  route_hierarchical: '>=0.4.21 <0.5.0'
  web_components: any
dev_dependencies:
  unittest: any
environment:
  sdk: ">=1.5.1"
transformers:
- angular
