name: angular_dart_demo
version: 0.0.1
dependencies:
  angular: any
  browser: any
  http_server: any
  js: any
  route_hierarchical: '>=0.4.18 <0.5.0'
  web_components: any
dev_dependencies:
  unittest: any
transformers:
- angular
